name: iOS

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Toolchain Dependencies
      working-directory: ${{runner.workspace}}/TeamTalk5/Build
      run: |
        brew update
        make depend-mac

    - name: Install TeamTalk Library Dependencies
      run: brew install doxygen

    - name: Build TeamTalk Library and Apps
      working-directory: ${{runner.workspace}}/TeamTalk5/Build
      run: make CMAKE_EXTRA="-DWEBRTC=OFF -DCMAKE_OSX_ARCHITECTURES=armv7 -DCMAKE_OSX_SYSROOT=iphoneos" CMAKE_GENERATOR="Unix Makefiles" BUILDDIR=build-ios-armv7 ios-build

    - name: Doxygen Documentation
      working-directory: ${{runner.workspace}}/TeamTalk5/Build
      run: make dox
