name: Windows-test

on: [push]

jobs:
  msvc:
    strategy:
      matrix:
        include:
          - name: VS2019Release32
            vmimage: windows-2019
            cmakeplatform: Win32
          - name: VS2019Release64
            vmimage: windows-2019
            cmakeplatform: x64
    runs-on: ${{ matrix.vmimage }}
    name: ${{ matrix.name }}
    steps:
    - uses: actions/checkout@v2
    - name: Init TeamTalk Client submodules
      working-directory: ${{runner.workspace}}/TeamTalk5
      run: |
        git submodule update --init --recursive Client
    - name: Generate CMake Projects
      working-directory: ${{runner.workspace}}
      run: >-
        cmake -S TeamTalk5 -B output -A ${{ matrix.cmakeplatform }}
        -DBUILD_TEAMTALK_CORE=ON
        -DCATCH_UNITTEST=OFF
        -DLIBVPX=OFF
        -DOPUSTOOLS=OFF
        -DOPUS=OFF
        -DSPEEX=OFF
        -DSPEEXDSP=OFF
        -DOGG=OFF
        -DPORTAUDIO=OFF
        -DWEBRTC=OFF
    - name: Build CMake Projects
      working-directory: ${{runner.workspace}}
      run: |
        cmake --build output
        
